# Generated by Django 5.2.14 on 2026-08-27 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduAgentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_tasks', models.IntegerField()),
                ('in_progress_tasks', models.IntegerField()),
                ('total_tasks', models.IntegerField()),
                ('observed_logs', models.TextField()),
                ('performance_analysis', models.TextField()),
                ('path_adjustment', models.TextField()),
                ('recommendation', models.TextField()),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eduagent_reviews', to='students.learningpath')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eduagent_reviews', to='students.studentprofile')),
            ],
        ),
    ]
