# Generated by Django 5.2.14 on 2026-08-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_eduagentreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduagentreview',
            name='decision',
            field=models.TextField(blank=True),
        ),
    ]
